port: 4000
host: localhost
safe: false
destination: build

### site serving configuration ###
exclude: [CNAME, Gemfile, Gemfile.lock, LICENSE.md, README.md, package-lock.json, vendor, .gitignore, cibuild.sh, .prettierrc]
permalink: /:title
timezone: null
lsi: false

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

sass:
  sass_dir: css

plugins:
  - jekyll-paginate
  - jekyll-feed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"

### content configuration ###
url:         "http://blog.jabref.org"
title:       "JabRef | Blog"
keywords:    "JabRef, blog"
description: "The blog of the literature management software JabRef"
source_link: "https://github.com/JabRef/blog.jabref.org/"
favicon:      "img/favicon.ico"

jekyll_analytics:
  GoogleAnalytics:
  id: UA-74055103-5
  anonymizeIp: true

repository: JabRef/blog.jabref.org

paginate: 5
paginate_path: "/page:num/"
